name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.2

      - name: Java
        run: javac HelloWorld.java && java HelloWorld
        working-directory: ./java
