name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.0.2

      - name: Configure GCC "latest"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
          cc: 1

      - name: C
        run: gcc HelloWorld.c -o HelloWorld && ./HelloWorld
        working-directory: ./c

      - name: C++
        run: g++ HelloWorld.cpp -o HelloWorld && ./HelloWorld
        working-directory: ./cpp

      - name: Configure Go 1.18.3
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'
          check-latest: true

      - name: Go
        run: go build HelloWorld.go && ./HelloWorld
        working-directory: ./go

      - name: Configure JDK 11
        uses: actions/setup-java@v3.4.0
        with:
          distribution: temurin
          java-version: 11

      - name: Java
        run: javac HelloWorld.java && java HelloWorld
        working-directory: ./java

      - name: Configure Kotlin 1.7.0
        uses: fwilhe2/setup-kotlin@0.3.0
        with:
          version: 1.7.0

      - name: Kotlin
        run: kotlinc HelloWorld.kt && kotlin HelloWorldKt
        working-directory: ./kotlin

      - name: Configure Python 3.8.13
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.8.13
          architecture: x64

      - name: Python
        run: python HelloWorld.py
        working-directory: ./python

      - name: Configure Swift "latest"
        uses: swift-actions/setup-swift@v1

      - name: Swift
        run: swiftc HelloWorld.swift && ./HelloWorld
        working-directory: ./swift
