name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.1.0

      - name: Bash
        run: bash HelloWorld.sh
        working-directory: ./bash

      - name: Configure GCC "latest"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
          cc: 1

      - name: C
        run: gcc HelloWorld.c -o HelloWorld && ./HelloWorld
        working-directory: ./c

      - name: Configure Cobol "stable"
        uses: fabasoad/setup-cobol-action@v1.4.1

      - name: Cobol
        run: cobc -x -free -o HelloWorld HelloWorld.cbl && ./HelloWorld
        working-directory: ./cobol

      - name: C++
        run: g++ HelloWorld.cpp -o HelloWorld && ./HelloWorld
        working-directory: ./cpp

      - name: Configure Dart "stable"
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Dart
        run: dart HelloWorld.dart
        working-directory: ./dart

      - name: Configure Go 1.18.3
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
          check-latest: true

      - name: Go
        run: go build HelloWorld.go && ./HelloWorld
        working-directory: ./go

      - name: Configure Haskell 8.8.4
        uses: haskell/actions/setup@v2
        with:
          ghc-version: 8.8.4

      - name: Haskell
        run: ghc HelloWorld.hs -o HelloWorld && ./HelloWorld
        working-directory: ./haskell

      - name: Configure JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 11

      - name: Java
        run: javac HelloWorld.java && java HelloWorld
        working-directory: ./java

      - name: Configure Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: JavaScript
        run: node HelloWorld.js
        working-directory: ./javascript

      - name: Configure Kotlin 1.7.0
        uses: fwilhe2/setup-kotlin@0.4.0
        with:
          version: 1.7.0

      - name: Kotlin
        run: kotlinc HelloWorld.kt && kotlin HelloWorldKt
        working-directory: ./kotlin

      - name: Configure Lua 5.3.5
        uses: xpol/setup-lua@v0.3
        with:
          lua-version: 5.3.5

      - name: Lua
        run: lua HelloWorld.lua
        working-directory: ./lua

      - name: Configure Clang "latest"
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
          cc: 1

      - name: Objective-C
        run: clang HelloWorld.m -o HelloWorld && ./HelloWorld
        working-directory: ./objective-c

      - name: Configure Perl 5.34
        uses: shogo82148/actions-setup-perl@v1.18.3
        with:
          perl-version: 5.34

      - name: Perl
        run: perl HelloWorld.pl
        working-directory: ./perl

      - name: Configure Python 3.8.13
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8.13
          architecture: x64

      - name: Python
        run: python HelloWorld.py
        working-directory: ./python

      - name: Configure R
        uses: r-lib/actions/setup-r@v2

      - name: R
        run: Rscript HelloWorld.r
        working-directory: ./r

      - name: Configure Racket 8.5
        uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: 8.5

      - name: Racket
        run: racket HelloWorld.rkt
        working-directory: ./racket

      - name: Configure Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Ruby
        run: ruby HelloWorld.rb
        working-directory: ./ruby

      - name: Confgure Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: Rust
        run: rustc HelloWorld.rs && ./HelloWorld
        working-directory: ./rust

      - name: Configure Swift "latest"
        uses: swift-actions/setup-swift@v1

      - name: Swift
        run: swiftc HelloWorld.swift && ./HelloWorld
        working-directory: ./swift

      - name: TypeScript
        run: node HelloWorld.ts
        working-directory: ./typescript
